export const clothes = [
    {
        "position":1,
        "title":"Clothes",
        "epid":"124573663139",
        "link":"https://www.ebay.com/itm/Clothes/124573663139",
        "image":"https://i.ebayimg.com/thumbs/images/g/6QAAAOSw6rZftV8b/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":false,
        "item_location":"Sri Lanka",
        "shipping_cost":12,
            "price":20,
    },
    {
        "position":2,
        "title":"Small - Large Pet Dog Adidog Winter Clothes Sweater Hoodie Shirt Jacket Jumpsuit",
        "epid":"174330049890",
        "link":"https://www.ebay.com/itm/Small-Large-Pet-Dog-Adidog-Winter-Clothes-Sweater-Hoodie-Shirt-Jacket-Jumpsuit/174330049890",
        "image":"https://i.ebayimg.com/thumbs/images/g/RR0AAOSwa3FcFfLg/s-l225.jpg",
        "hotness":"12+ sold",
        "condition":"New (Other)",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "item_location":"China",
        "sponsored":true,
        "price":4.8
    },
    {
        "position":3,
        "title":"Toddler 2T Girls Skirt Childrens Cotton baby clothes infant",
        "epid":"303602644719",
        "link":"https://www.ebay.com/itm/Toddler-2T-Girls-Skirt-Childrens-Cotton-baby-clothes-infant/303602644719",
        "image":"https://i.ebayimg.com/thumbs/images/g/k3sAAOSwPile8A-~/s-l225.jpg",
        "condition":"Pre-Owned",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":false,
        "item_location":"United States",
        "sponsored":true,
        "price":7.95
    },
    {
        "position":4,
        "title":"Cute Warm Fleece Dog Jumpsuit Pajamas Clothes Puppy Dog Sweater Cat Coat Costume",
        "epid":"303353901466",
        "link":"https://www.ebay.com/itm/Cute-Warm-Fleece-Dog-Jumpsuit-Pajamas-Clothes-Puppy-Dog-Sweater-Cat-Coat-Costume/303353901466",
        "image":"https://i.ebayimg.com/thumbs/images/g/LL8AAOSw~K9dxQeI/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "item_location":"China",
        "sponsored":true,
        "price":6.29

    },
    {
        "position":5,
        "title":"Toddler girl T Shirt Long Pants Tracksuit Outfits Clothes Set.",
        "epid":"363291604363",
        "link":"https://www.ebay.com/itm/Toddler-girl-T-Shirt-Long-Pants-Tracksuit-Outfits-Clothes-Set/363291604363",
        "image":"https://i.ebayimg.com/thumbs/images/g/e6IAAOSw~O5gJ~HV/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":false,
        "item_location":"United States",
        "price":12.99,
    },
    {
        "position":6,
        "title":"Lot of Baby Girl Clothes Size 3 Months Carter’s",
        "epid":"114685914825",
        "link":"https://www.ebay.com/itm/Lot-of-Baby-Girl-Clothes-Size-3-Months-Carter-s/114685914825",
        "image":"https://i.ebayimg.com/thumbs/images/g/6ZgAAOSwz19gKo1S/s-l225.jpg",
        "condition":"Pre-Owned",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":false,
        "item_location":"United States",
        "shipping_cost":7,
        "price":20,
    },
    {
        "position":7,
        "title":"newborn baby boy clothes carters",
        "epid":"124574350161",
        "link":"https://www.ebay.com/itm/newborn-baby-boy-clothes-carters/124574350161",
        "image":"https://i.ebayimg.com/thumbs/images/g/E2AAAOSwZsRgKei9/s-l225.jpg",
        "condition":"Pre-Owned",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":false,
        "item_location":"United States",
        "price":10,
    },
    {
        "position":8,
        "title":"Lace Flower Girl Dress Kids Party Princess Birthday Party Tutu Clothes Size 3-8",
        "epid":"254186819722",
        "link":"https://www.ebay.com/itm/Lace-Flower-Girl-Dress-Kids-Party-Princess-Birthday-Party-Tutu-Clothes-Size-3-8/254186819722",
        "image":"https://i.ebayimg.com/thumbs/images/g/hZoAAOSwT9lcefTm/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "item_location":"United States",
        "price":10.88
    },
    {
        "position":9,
        "title":"Clothes And Accessories For Barbie Doll 18 Pcs Pajamas Lace Lingerie Night Dress",
        "epid":"15042931382",
        "link":"https://www.ebay.com/itm/Clothes-And-Accessories-For-Barbie-Doll-18-Pcs-Pajamas-Lace-Lingerie-Night-Dress/264929332706",
        "image":"https://i.ebayimg.com/thumbs/images/g/GN0AAOSwne1fpxyr/s-l225.jpg",
        "hotness":"78 sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":false,
        "item_location":"China",
        "price":10.99
    },
    {
        "position":10,
        "title":"Barbie Doll Clothes Lot",
        "epid":"184629638826",
        "link":"https://www.ebay.com/itm/Barbie-Doll-Clothes-Lot/184629638826",
        "image":"https://i.ebayimg.com/thumbs/images/g/PuUAAOSwjDpgCHBu/s-l225.jpg",
        "hotness":"4 watchers",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "item_location":"United States",
        "shipping_cost":3.5,
        "price":8.5
    },
]; 