export const foods = [
    {
        "position":1,
        "title":"Freeze Dried Fully Cooked Scrambled US Eggs Camping Hiking Survival Storage Food",
        "epid":"114194962319",
        "link":"https://www.ebay.com/itm/Freeze-Dried-Fully-Cooked-Scrambled-US-Eggs-Camping-Hiking-Survival-Storage-Food/114194962319",
        "image":"https://i.ebayimg.com/thumbs/images/g/7qcAAOSwJcden1c0/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":true,
        "item_location":"United States",
        "sponsored":true,
            "price":24.5,
    },
    {
        "position":2,
        "title":"BULK Freeze Dried Uncooked Sirloin Steaks Camping Hiking Survival Storage Food",
        "epid":"143526290334",
        "link":"https://www.ebay.com/itm/BULK-Freeze-Dried-Uncooked-Sirloin-Steaks-Camping-Hiking-Survival-Storage-Food/143526290334",
        "image":"https://i.ebayimg.com/thumbs/images/g/6WcAAOSwfdhePQLl/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":true,
        "item_location":"United States",
        "sponsored":true,
        "price":36.5
    },
    {
        "position":3,
        "title":"BULK Freeze Dried 1/3-lb Hamburger Patties Camping Hiking Survival Storage Food!",
        "epid":"143547700926",
        "link":"https://www.ebay.com/itm/BULK-Freeze-Dried-1-3-lb-Hamburger-Patties-Camping-Hiking-Survival-Storage-Food/143547700926",
        "image":"https://i.ebayimg.com/thumbs/images/g/vC4AAOSwFz9eYGBg/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":true,
        "item_location":"United States",
        "sponsored":true,
        "price":34.65
    },
    {
        "position":4,
        "title":"Freeze Dried fully cooked sliced cheesecake Camping Hiking Survival Storage Food",
        "epid":"114108461070",
        "link":"https://www.ebay.com/itm/Freeze-Dried-fully-cooked-sliced-cheesecake-Camping-Hiking-Survival-Storage-Food/114108461070",
        "image":"https://i.ebayimg.com/thumbs/images/g/1mEAAOSwAGxeQdwd/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":true,
        "item_location":"United States",
        "sponsored":true,
        "price":27.3

    },
    {
        "position":5,
        "title":"BULK Freeze Dried Sliced Fresh Avocado Camping Hiking Survival Storage Food USA!",
        "epid":"143526154579",
        "link":"https://www.ebay.com/itm/BULK-Freeze-Dried-Sliced-Fresh-Avocado-Camping-Hiking-Survival-Storage-Food-USA/143526154579",
        "image":"https://i.ebayimg.com/thumbs/images/g/U6YAAOSwXKdePL0K/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":true,
        "item_location":"United States",
        "price":38.25
    },
    {
        "position":6,
        "title":"BULK Freeze Dried Fully Cooked Sliced Ham Camping Hiking Survival Storage Food",
        "epid":"312983519670",
        "link":"https://www.ebay.com/itm/BULK-Freeze-Dried-Fully-Cooked-Sliced-Ham-Camping-Hiking-Survival-Storage-Food/312983519670",
        "image":"https://i.ebayimg.com/thumbs/images/g/6FcAAOSwDudePOv9/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":true,
        "item_location":"United States",
        "sponsored":true,
        "price":34.7
    },
    {
        "position":7,
        "title":"Emergency Food Supply 4 Person Kit 55 Serving Storage Quick Meal Survival Bucket",
        "epid":"2308904496",
        "link":"https://www.ebay.com/itm/Emergency-Food-Supply-4-Person-Kit-55-Serving-Storage-Quick-Meal-Survival-Bucket/193876289225",
        "image":"https://i.ebayimg.com/thumbs/images/g/DTsAAOSwfDBgGbLI/s-l225.jpg",
        "hotness":"Last one",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "item_location":"United States",
        "price":26.65
    },
    {
        "position":8,
        "title":"Freeze Dried Uncooked US Salmon Filets Camping Hiking Survival Storage Food Fish",
        "epid":"143539292529",
        "link":"https://www.ebay.com/itm/Freeze-Dried-Uncooked-US-Salmon-Filets-Camping-Hiking-Survival-Storage-Food-Fish/143539292529",
        "image":"https://i.ebayimg.com/thumbs/images/g/vOQAAOSwzzBeUdPH/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":true,
        "item_location":"United States",
        "price":36.8
    },
    {
        "position":9,
        "title":"BULK Freeze Dried US/ID Hash Brown Potatoes Camping Hiking Survival Storage Food",
        "epid":"114643284274",
        "link":"https://www.ebay.com/itm/BULK-Freeze-Dried-US-ID-Hash-Brown-Potatoes-Camping-Hiking-Survival-Storage-Food/114643284274",
        "image":"https://i.ebayimg.com/thumbs/images/g/IikAAOSwNVZgCfpV/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":false,
        "free_returns":true,
        "item_location":"United States",
        "price":22.5
    },
    {
        "position":10,
        "title":"Mountain House Freeze Dried Food",
        "epid":"333886529342",
        "link":"https://www.ebay.com/itm/Mountain-House-Freeze-Dried-Food/333886529342",
        "image":"https://i.ebayimg.com/thumbs/images/g/qfUAAOSwUvpgJV-z/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":true,
        "bid_count":1,
        "buy_it_now":false,
        "free_returns":false,
        "item_location":"United States",
        "shipping_cost":8.45,
        "price":8
    },
]; 