export const
  products =  [
    {
        _id: '1',
        name: '5" Triangle Instrument With Beater',
        category: 'Musical Instruments',
        image: '/images/d1.jpg',
        price: 5,
        brand: ' YASATEAO',
        rating: 4.5,
        numReviews: 2,
        countInStock: 6,
        description: '❤ Made with heavy-duty steel for long, resonating tone.❤ Help to train children hearing and enhance children musical culture.Children will learn a sense of rhythm and beat with a little practice. ❤ SIZE: 5" equilateral triangle with a beater. ❤ HANGING HANDLE:Plastic handle that hangs from your finger giving the triangle balance❤MUSICAL TRIANGLE:An ideal instrument for novice musicians and school children that has been enjoyed for generations.It can be a nice gift for your kids,classmates, friends and family',
        reviews:[
          { _id: 1,
            name:"	Lady Lemora",
          rating:5,
          comment:"Wow! Cant believe how great quality this item is for the price. Well worth the money. Very happy and would definitely recommend. Ideal for all ages too!"},
          { _id: 2,
            name:"	Gemma",
          rating:5,
          comment:"Great value for money. Great product, well made. Brought for my nephew to make lots of noise and have fun. Ticked all the boxes."},
        ],
      },
      {
        _id: '2',
        name: 'Singing Bowl',
        category: 'Musical Instruments',
        image: '/images/d2.jpg',
        price: 19.99,
        brand: ' YASATEAO',
        rating: 4.2,
        numReviews: 1,
        description: '【Satisfaction Guaranteed】- We are confident in protecting your home against the unwanted pest. If youre not completely satisfied, contact us and we will give you a satisfactory answer! 1-YEAR WARRANTY guaranteed, lifetime tech support, totally NO RISK order! "Add to Basket" now!',
        reviews:[
          {_id:1,
          name:"Kerry",
          rating:2,
          comment:"I am in love with my new singing bowl. I use these for meditations and to bring a higher vibration into my space. It is as beautiful as it looks and has an amazingly, beautiful tune to it. Would recommend! I was in a fire in 2015 and this helps with my anxiety. Thank you so much x"},
        ],
      },
      {
        _id: '3',
        name: '24 hole polyphonic harmonica',
        category: 'Musical Instruments',
        image: '/images/d3.jpg',
        price: 45,
        brand: 'SWAN',
        rating: 4.5,
        numReviews: 1,
        countInStock: 6,
        description: 'item description:xxxxxxxxx',
        reviews:[
            {_id:1,
            name:"username1",
            rating:2,
            comment:"comment123"},
          ],
      }, {
        _id: '4',
        name: 'Philips Avent SCF870/21 Babyfood Steamer and Blender',
        category: 'Electronics',
        image: '/images/d4.jpg',
        price: 42,
        brand: ' Philips',
        rating: 4.5,
        numReviews: 3,
        countInStock: 6,
        description: 'Mealtimes made easy: From steaming to blending all-in-one handy jarPrepare healthy meals for your little one: Distinct way of steaming which keeps in all the goodnessMeals for every weaning stage: From pureed to chunky, helping you to prepare varied food for every step of the wayEasy to use: Makes food preparation simple with only a few settings and separate parts',
        reviews:[
            {_id:1,
            name:"	Amazon Customer",
            rating:3,
            comment:"All the time and utility of having a combined steamer and blender totally wasted by being nearly impossible to clean. Residue builds up everywhere, and all the nooks and crannies are very awkward to reach. Dirt seems to be caught and embedded in the plastic of the lid and filter, at times staining the surface.Very unhygienic, especially when designed for baby food."},
            {_id:2,
                name:"Sorin",
                rating:2,
                comment:"Either we got a refurbished product advertised as new, or the design is flawed. It started to leak a burnt oil-like liquid from the bottom cover within less than 3 weeks of using. Also leaked between the water tank base and the bowl, resulting in burning my wife’s hands. A total mess and a hazardous product to say the least. Wish I could have returned it, but as we bought it months in advance before we needed it, I was unable to do so. We bought the newer version and it works just fine. But Phillips actually changed the water tank design and the bowl valve (it’s no longer a rubber ring). Which really makes me think the design on this model is poor and prone to fail."},
                {_id:3,
                    name:"	Sally",
                    rating:3,
                    comment:"I had high hopes for this blender. It was really impressive at first. The steamer works really well but the blender soon turned dodgy. Sometimes it wouldn’t blend and I wondered if I was doing something wrong but I wasn’t. After 2 months, the blender stopped working altogether. I’m incredibly disappointed and getting a replacement.."},
                    
          ],
      },
      {
        _id: '5',
        name: 'Philips Shaver Series 3000 with Powercut Blades',
        category: 'Electronics',
        image: '/images/d5.jpg',
        price: 64,
        brand: ' Philips',
        rating: 4.5,
        numReviews: 4,
        countInStock: 6,
        description: '5D pivot & flex heads follow curves for a more comfortable shavePower cut blades have been engineered for a consistent clean shave27 self-sharpening blades ensure an easy to maintain productFinish your look with our built-in trimmer. Ideal for maintaining your moustache and trimming your sideburns!Cordless shaving for up to 60 minutes after an hourattery-Powered',
        reviews:[
            {_id:1,
            name:"R. C. Lobo",
            rating:2,
            comment:"After buying a fancy Philips Shaver series 5000 I was completely disappointed. After shaving there was a lot of unshaved stubble, it took for ages and my skin ended up red and sore. I've been using Philips shavers all my life and I was both surprised and frustrated with this shaver lack of performance.I returned it, thanks amazon for the hassle free experience, and I bought this one, very similar to my old one, a HQ 7310 series 7000, and what a difference.This one is as good as my old one, quick, no sore skin, as it has to be. I have a beard like the guys from the film 300, and this shaver leaves my face smooth like a baby.I recommend this product, very happy with this purchase."},
            {_id:2,
                name:"	john bristow",
                rating:2,
                comment:"'ve had a philishave since 1988 and NEVER have I changed the blades. They definitely begun to be useless some time ago and even though I'd sharpened them they were becoming useless so I decided after all to buy a new razor. The 3000 is superb, a couple of minutes and I've got skin feeling as smooth as ………………………!"},
                {_id:3,
                    name:"Richard",
                    rating:2,
                    comment:" It mostly works."},
                    {_id:4,
                        name:"Mike",
                        rating:2,
                        comment:"aaaThis razor lasted just 11 months then died and apparently it doesn't even have a one year warranty. Unreliable product to be avoided and if it goes wrong you are on your own.aaaaaa"},
          ],
      },
      {
        _id: '6',
        name: 'Iconbit City GT Foldable Electric 350W Motor Kick Scooter',
        category: 'Electronics',
        image: '/images/d6.jpg',
        price: 319,
        brand: ' Iconbit',
        rating: 4.5,
        numReviews: 1,
        countInStock: 6,
        description: 'bout this item8.5” wheels with double shock absorber350w motorRear Disc BrakeSpeed up to 25Km/hIPX4 rating',
        reviews:[
            {_id:1,
            name:"Minhaj",
            rating:2,
            comment:"Very bad. Do not buy."},
          ],
      },
      {
        _id: '7',
        name: 'All-new Echo Dot (4th generation)',
        category: 'Electronics',
        image: '/images/d7.jpg',
        price: 64,
        brand: '',
        rating: 4.5,
        numReviews: 7,
        countInStock: 6,
        description: 'Meet the all-new Echo Dot—our most popular smart speaker with Alexa. The sleek, compact design delivers crisp vocals and balanced bass for full sound. Voice control your entertainment—stream songs from Amazon Music, Apple Music, Spotify, Deezer and more. Play music, audiobooks and podcasts throughout your home with multi-room music.Ready to help—ask Alexa to tell a joke, play music, answer questions, play the news, check the weather, set alarms and more.Control your smart home—use your voice to turn on lights, adjust thermostats and lock doors with compatible devices.',
        reviews:[
            {_id:1,
            name:"susan block",
            comment:"If you like music, cooking, or checking facts you will enjoy this.The one draw back I did find, my son has one in his bedroom, so you could not shout instructions too loud to the one down stairs because it would set off the one in his bedroom.The music selection is affected by your service. Apple play is great my son has that but you have to pay extra.So we used Spotify as free, you get the odd advert.My husband loves cooking and uses it a lot for keeping tabs on cooking times."},
            {_id:2,
                name:"claire plant",
                comment:"I already had an echo but when I saw this echo 4 on offer I spoilt myself and I love it I use her so much more than my old one, this one is just like a friend ❤."},
                {_id:3,
                    name:"ABC",
                    rating:2,
                    comment:"Very Good."},
                    {_id:4,
                        name:"ASDAS",
                        rating:2,
                        comment:"Very Good."},
                        {_id:5,
                            name:"CDADFA",
                            rating:4,
                            comment:"Very Good."},
                            {_id:6,
                                name:"SAD",
                                rating:4,
                                comment:"Very Good."},
                                {_id:7,
                                    name:"DEC",
                                    rating:4,
                                    comment:"Very Good."},
            ],
      },
      {
        _id: '8',
        name: 'Echo Show 8',
        category: 'Electronics',
        image: '/images/d8.jpg',
        price: 135,
        brand: '',
        rating: 4.5,
        numReviews: 2,
        countInStock: 6,
        description: 'Alexa can show you more: with an 8" HD screen and stereo sound, Alexa can help you manage your day at a glance.Connect with video calling and messaging: call friends and family who have the Alexa app or an Echo device with a screen. Make announcements to other devices in your home.Be entertained: ask Alexa to show you TV programmes, films or the news. Listen to radio stations, podcasts and audiobooks.Control your smart home: voice control compatible devices, or manage them on the easy-to-use display. Ask Alexa to show you security cameras, control lights and adjust thermostats.Make it yours: display your Amazon photo albums and customise your Home screen. Create morning routines to start your day. Made to fit your life: cook step-by-step recipes. Easily update to-do lists and calendars. Glance at weather and traffic on your way out.',
        reviews:[
            {_id:1,
            name:"Rob",
            comment:"I bought the Echo 8, as an alarm, and wanted a bigger screen to see the time during the night, but the clock face is only available on the smaller Echo 5. I got it in the Black Friday sale for £59. I’m in a dilemma, i don’t know whether to send it back, or hope Amazon updates the Echo with new software that would mirror the Echo 5."},
             {_id: 2, 
            name: "Shane Farringdon",
            comment: "I pre ordered this device after asking on Amazon forum and getting a reply from an Amazon rep that the show 8 will do the same as the show 5 only bigger screen, i wanted the large face clock with date and ideally the day. but as the show 5 i would settle for a large clock and date in middle of the screen .. But after paying double the BF price i found it was a lie the show 8 is not the same as the show 5 far from it.. So if you are looking for a large clock face then don't buy this .."
              }
        ],
      },
      {
        _id: '9',
        name: 'IFOAIR 120°USB Webcam',
        category: 'Electronics',
        image: '/images/d9.jpg',
        price: 39.9,
        brand: ' IFOAIR',
        rating: 4.5,
        numReviews: 2,
        countInStock: 6,
        description: '【Auto Light Correction & Plug and Play】The PC webcam is helpful in dim or overexposed situations. It can adjust the light automatically, so you can always look your best wherever you are. It has a manual focus rather than AF to be faster and more accurate. No additional driver is required. It supports USB 3.1 and works with different mainstream systems and software',
        reviews:[
            {_id:1,
            name:"Bob",
            rating:2,
            comment:"good"},
            {_id:2,
                name:"J",
                rating:2,
                comment:"very good"}
          ],
      },
      {
        _id: '10',
        name: 'Electric remote control aircraft',
        category: 'Electronics',
        image: '/images/d6.jpg',
        price: 135,
        brand: ' ZHIXIANG',
        rating: 4.5,
        numReviews: 2,
        countInStock: 6,
        description: 'Amazon Smart Plug works with Alexa to add voice control to any electrical socket.Schedule lights, coffee machines and appliances to turn on and off automatically, or control them remotely when you’re away. Simple to set up and use: plug in, open the Alexa app and start using your voice.No smart home hub required: set up routines and schedules through the Alexa app.Certified for Humans: Struggle-free, tinker-free and stress-free. No patience needed—it',
        reviews:[
            {_id:1,
            name:"	Scotsann",
            rating:2,
            comment:"Unsafe. Mine has just tripped the whole of my downstairs and there is a nasty burning smell. Plug is black in sections, yet another return back to Amazon. It would be good to know how many of these units are causing electric faults."},
            {_id:2,
                name:"Stephen Fletcher",
                rating:2,
                comment:"Used to control mini Christmas tree lights - a very small loadAfter just 1 day it tripped all electrics in our house and burnt Amazon plug 🔥. A quick look through reviews shows I’m not the only customer - is this a known problem?"}
          ],
      },
      {
        _id: '11',
        name: 'JJA keyboard pianos',
        category: 'Musical Instruments',
        image: '/images/d11.jpg',
        price: 12,
        brand: '',
        rating: 4.5,
        numReviews: 4,
        countInStock: 6,
        description: '61 Keys Multifunctional Portable Microphone, Musical Organ Instrument Electronic Piano Keyboard, Suitable Kids Toy Beginner Child & Adult',
        reviews:[
            {_id:1,
            name:"	oksana",
            rating:3,
            comment:"it looks better on the pic than it actually is. Very light and plastic looking."},
            {_id:2,
                name:"userJ",
                rating:2,
                comment:"very good"},
                {_id:3,
                  name:"usera",
                  rating:4,
                  comment:"very good"},
                  {_id:4,
                    name:"userb",
                    rating:5,
                    comment:"very good"}
  
          ],
      },
      {
        _id: '12',
        name: 'Tambourine for adults ',
        category: 'Musical Instruments',
        image: '/images/d12.jpg',
        price: 14,
        brand: '',
        rating: 4.5,
        numReviews: 2,
        countInStock: 6,
        description: '10 inch Hand Held Drum Bell Birch Metal Jingles Percussion Gift Musical Educational Instrument for Church KTV Party (10 inch)',
        reviews:[
            {_id:1,
            name:"kerry-anne middlemore",
            rating:5,
            comment:"Everyone should have a tambourine"},
            {_id:2,
                name:"Andy_S.",
                rating:5,
                comment:"very gNot much i can say about this but definitely worth the money - DO NOT GIVE TO CHILDREN (seriously, you'll regret it).ood"}
          ],
      },

]