export const products = [
    {
        "position":1,
        "title":"SanDisk Ultra New 32GB micro SD SDHC Class10 Flash Memory Card 100MB/s",
         "epid":"8030522363",
          "link":"https://www.ebay.com/itm/SanDisk-Ultra-New-32GB-micro-SD-SDHC-Class10-Flash-Memory-Card-100MB-s/332050873554",
          "image":"https://i.ebayimg.com/thumbs/images/g/4eAAAOSwQ~VfWKfo/s-l225.jpg",
          "hotness":"10,000+ sold",
           "condition":"Brand New",
           "is_auction":false,
           "buy_it_now":true,
          "free_returns":false,
           "item_location":"Taiwan",
             "sponsored":true,
            "price":5.57,
    },
    {
        "position":2,
        "title":"SanDisk Micro SD Card 16GB 32GB 64GB 128GB TF Class 10 for Smartphones & Tablets",
        "epid":"202535485899",
        "link":"https://www.ebay.com/itm/SanDisk-Micro-SD-Card-16GB-32GB-64GB-128GB-TF-Class-10-for-Smartphones-Tablets/202535485899",
        "image":"https://i.ebayimg.com/thumbs/images/g/u6cAAOSwMSRfZ8yd/s-l225.jpg",
        "hotness":"10,000+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "item_location":"United States",
        "sponsored":true,
        "price":6.99
    },
    {
        "position":3,
        "title":"Kingston Micro SD Card 16GB 32GB 64GB 128GB TF Class 10 for Smartphones",
        "epid":"202807227674",
        "link":"https://www.ebay.com/itm/Kingston-Micro-SD-Card-16GB-32GB-64GB-128GB-TF-Class-10-for-Smartphones/202807227674",
        "image":"https://i.ebayimg.com/thumbs/images/g/DhsAAOSwJlRez6tM/s-l225.jpg",
        "hotness":"6,915+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "sponsored":true,
        "price":6.99
    },
    {
        "position":4,
        "title":"SanDisk Micro SD Card 16GB 32GB 64GB 128GB TF Class 10 for Smartphones",
        "epid":"203007357367",
        "link":"https://www.ebay.com/itm/SanDisk-Micro-SD-Card-16GB-32GB-64GB-128GB-TF-Class-10-for-Smartphones/203007357367",
        "image":"https://i.ebayimg.com/thumbs/images/g/ReEAAOSwiE9e0oYK/s-l225.jpg",
        "hotness":"1,576+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "sponsored":true,
        "price":6.99

    },
    {
        "position":5,
        "title":"Sandisk Micro SD Card Ultra Memory Card 32GB 64GB 128GB Smartphones Tablet lot",
        "epid":"233599133856",
        "link":"https://www.ebay.com/itm/Sandisk-Micro-SD-Card-Ultra-Memory-Card-32GB-64GB-128GB-Smartphones-Tablet-lot/233599133856",
        "image":"https://i.ebayimg.com/thumbs/images/g/AswAAOSwPMley-Gz/s-l225.jpg",
        "hotness":"2,004+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "price":4.95
    },
    {
        "position":6,
        "title":"SanDisk 512GB Micro SD Ultra microSDXC UHS-I A1 Memory Card",
        "epid":"13032814391",
        "link":"https://www.ebay.com/itm/SanDisk-512GB-Micro-SD-Ultra-microSDXC-UHS-I-A1-Memory-Card/303855242096",
        "image":"https://i.ebayimg.com/thumbs/images/g/OU0AAOSwRrpf2sfL/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "sponsored":true,
        "price":47.99
    },
    {
        "position":7,
        "title":"Sandisk Micro SD Card 64GB 128GB 256GB 512GB Extreme Pro Ultra Memory Cards lot",
        "epid":"324275407863",
        "link":"https://www.ebay.com/itm/Sandisk-Micro-SD-Card-64GB-128GB-256GB-512GB-Extreme-Pro-Ultra-Memory-Cards-lot/324275407863",
        "image":"https://i.ebayimg.com/thumbs/images/g/ICEAAOSwUKRfR9mU/s-l225.jpg",
        "hotness":"202+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "price":4.04
    },
    {
        "position":8,
        "title":"SanDisk Micro SD Card 16GB 32GB 64GB 128GB TF Class 10 for Smartphones Tablets",
        "epid":"9007904572",
        "link":"https://www.ebay.com/itm/SanDisk-Micro-SD-Card-16GB-32GB-64GB-128GB-TF-Class-10-for-Smartphones-Tablets/324273516399",
        "image":"https://i.ebayimg.com/thumbs/images/g/mFYAAOSwb2xc-H1q/s-l225.jpg",
        "hotness":"4,136+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "price":5.23
    },
    {
        "position":9,
        "title":"64/128/256/512GB/1TB Universal Micro SD SDXC TF Flash Memory Card Class 10",
        "epid":"124509918321",
        "link":"https://www.ebay.com/itm/64-128-256-512GB-1TB-Universal-Micro-SD-SDXC-TF-Flash-Memory-Card-Class-10/124509918321",
        "image":"https://i.ebayimg.com/thumbs/images/g/5sIAAOSwggRftZk0/s-l225.jpg",
        "hotness":"98+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "price":7.93
    },
    {
        "position":10,
        "title":"Samsung EVO+ Micro SD Card Memory Card 32GB 64GB 128GB 256GB 512GB Wholesale lot",
        "epid":"324159010823",
        "link":"https://www.ebay.com/itm/Samsung-EVO-Micro-SD-Card-Memory-Card-32GB-64GB-128GB-256GB-512GB-Wholesale-lot/324159010823",
        "image":"https://i.ebayimg.com/thumbs/images/g/Co0AAOSwuwJfLG9r/s-l225.jpg",
        "hotness":"354+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "price":7.74
    },
    {
        "position":11,
        "title":"256GB Micro Memory SD Card 4K Class10 Flash TF Card with Adapter Fr Phone USA",
        "epid":"363242830499",
        "link":"https://www.ebay.com/itm/256GB-Micro-Memory-SD-Card-4K-Class10-Flash-TF-Card-with-Adapter-Fr-Phone-USA/363242830499",
        "image":"https://i.ebayimg.com/thumbs/images/g/acQAAOSwH2Zfh~gG/s-l225.jpg",
        "hotness":"393+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "price":3.49
    },
    {
        "position":12,
        "title":"Kingston Micro SD Card 32GB 64GB 128GB TF Class 10 for Smartphones Tablets",
        "epid":"224073862386",
        "link":"https://www.ebay.com/itm/Kingston-Micro-SD-Card-32GB-64GB-128GB-TF-Class-10-for-Smartphones-Tablets/224073862386",
        "image":"https://i.ebayimg.com/thumbs/images/g/ohkAAOSwIThfB1Ch/s-l225.jpg",
        "hotness":"1,472+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "price":7.50
    },
    {
        "position":13,
        "title":"SanDisk Micro SD Memory Card High Speed TF 16GB 32GB 64GB 128GB 256GB MicroSD",
        "epid":"402403088443",
        "link":"https://www.ebay.com/itm/SanDisk-Micro-SD-Memory-Card-High-Speed-TF-16GB-32GB-64GB-128GB-256GB-MicroSD/402403088443",
        "image":"https://i.ebayimg.com/thumbs/images/g/~wUAAOSwAFlf9hUL/s-l225.jpg",
        "hotness":"127+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "item_location":"Canada",
        "shipping_cost":1.69,
        "price":1.57
    },
    {
        "position":14,
        "title":"[US] Sandisk Extreme Pro Memory Cards 512GB MicroSD Class 10",
        "epid":"363279016940",
        "link":"https://www.ebay.com/itm/US-Sandisk-Extreme-Pro-Memory-Cards-512GB-MicroSD-Class-10/363279016940",
        "image":"https://i.ebayimg.com/thumbs/images/g/HX0AAOSwxwZgF8Mt/s-l225.jpg",
        "hotness":"25+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "price":39.69
    },
    {
        "position":15,
        "title":"SanDisk 128GB 64GB Ultra Micro SD Class 10 TF SDXC Memory Card mobile Cellphone",
        "epid":"272255187242",
        "link":"https://www.ebay.com/itm/SanDisk-128GB-64GB-Ultra-Micro-SD-Class-10-TF-SDXC-Memory-Card-mobile-Cellphone/272255187242",
        "image":"https://i.ebayimg.com/thumbs/images/g/GQ0AAOSwj9dZvFTb/s-l225.jpg",
        "hotness":"2,297+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "sponsored":true,
        "price":6.38
    },
    {
        "position":16,
        "title":"SAMSUNG EVO Plus 256GB MicroSD Micro SDXC Class10 Flash Memory Card w/SD Adapter",
        "epid":"4031084099",
        "link":"https://www.ebay.com/itm/SAMSUNG-EVO-Plus-256GB-MicroSD-Micro-SDXC-Class10-Flash-Memory-Card-w-SD-Adapter/324456974872",
        "image":"https://i.ebayimg.com/thumbs/images/g/ISoAAOSwPOlgBiKP/s-l225.jpg",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "sponsored":true,
        "price":31.99
    },
    {
        "position":17,
        "title":"SanDisk Micro SD Card 8GB 16GB 32GB Memory Class 4 for Smartphones & Tablets",
        "epid":"202462926407",
        "link":"https://www.ebay.com/itm/SanDisk-Micro-SD-Card-8GB-16GB-32GB-Memory-Class-4-for-Smartphones-Tablets/202462926407",
        "image":"https://i.ebayimg.com/thumbs/images/g/hrgAAOSwwW9fRny0/s-l225.jpg",
        "hotness":"9,739+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "sponsored":true,
        "price":6.99
    },
    {
        "position":18,
        "title":"512GB Micro SD SDXC Class 10 memory Card",
        "epid":"353073613037",
        "link":"https://www.ebay.com/itm/512GB-Micro-SD-SDXC-Class-10-memory-Card/353073613037",
        "image":"https://i.ebayimg.com/thumbs/images/g/hMAAAOSww41euOL5/s-l225.jpg",
        "hotness":"826 sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":true,
        "sponsored":true,
        "price":16.99
    },
    {
        "position":19,
        "title":"SanDisk Micro SD Memory Card High Speed TF 4GB 8GB 16GB 32GB 64GB 128GB MicroSD",
        "epid":"202659875718",
        "link":"https://www.ebay.com/itm/SanDisk-Micro-SD-Memory-Card-High-Speed-TF-4GB-8GB-16GB-32GB-64GB-128GB-MicroSD/202659875718",
        "image":"https://i.ebayimg.com/thumbs/images/g/bwAAAOSwnA9f1RLJ/s-l225.jpg",
        "hotness":"277+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "item_location":"Canada",
        "price":0.78
    },
    {
        "position":20,
        "title":"Memory Card 4GB 8GB 16GB 32GB 64GB micro sd card Adepter/High speed Chip reader",
        "epid":"402493427518",
        "link":"https://www.ebay.com/itm/Memory-Card-4GB-8GB-16GB-32GB-64GB-micro-sd-card-Adepter-High-speed-Chip-reader/402493427518",
        "image":"https://i.ebayimg.com/thumbs/images/g/DasAAOSwnLhfh08H/s-l225.jpg",
        "hotness":"73+ sold",
        "condition":"Brand New",
        "is_auction":false,
        "buy_it_now":true,
        "free_returns":false,
        "item_location":"China",
        "price":3.71

    }
]; 